version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: log-symbols
    versions:
    - 4.0.0
    - 4.1.0
  - dependency-name: inquirer
    versions:
    - 7.3.3
  - dependency-name: chalk
    versions:
    - 4.1.0
